using Microsoft.CodeAnalysis;

namespace Nimble.Intrinsics.Generators;

[Generator]
internal partial class Generator : IIncrementalGenerator
{
    private const string CORE_HEADER = """
        // <auto-generated />
        #nullable enable
        
        using System.Diagnostics.CodeAnalysis;
        using System.Runtime.CompilerServices;
        using System.Runtime.Intrinsics;
        using System.Runtime.Intrinsics.X86;
        
        namespace Nimble.Runtime;
        
        public static unsafe partial class Intrinsics
        {
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(c => c.AddSource("Nimble.Runtime.Intrinsics.g.cs",          GenerateDefinition()));
        context.RegisterPostInitializationOutput(c => c.AddSource("Nimble.Runtime.Intrinsics.Add.g.cs",      GenerateAdd()));
        context.RegisterPostInitializationOutput(c => c.AddSource("Nimble.Runtime.Intrinsics.Multiply.g.cs", GenerateMultiply()));
    }

    private static string GenerateDefinition() => $$"""
            {{CORE_HEADER}}
                #if !NET8_0_OR_GREATER
                    // This attribute is a substitute for netstandard to compile.
                    private class ConstantExpectedAttribute : Attribute;
                #endif
            }
            """;
}
