<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;netstandard2.0</TargetFrameworks>

    <PackageId>dotnimble</PackageId>
    <Title>dotnimble</Title>
    <Description>Extends, improves and reimplements commonly used dotnet API's.</Description>

  </PropertyGroup>

  <ItemGroup>
    <Using Include="System.Collections" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
    <Using Include="System.Reflection" />
    <Using Include="System.Runtime.CompilerServices" />
  </ItemGroup>

</Project>
